### ISSUE TITLE
@0x/mesh-rpc-client has UnhandledPromiseRejectionWarning on init with invalid mesh URI

### ISSUE THREAD

**Issue by fragosti** [0xProject/0x-mesh#495]
With "@0x/mesh-rpc-client": "6.0.0-beta-v3"
This code:
```
let meshClient
try {
        meshClient = new WSClient(config.MESH_WEBSOCKET_URI);
} catch (err) {
        logger.error(err);
}
```
Results in this unhandledPromiseRejectionWarning.

```
(node:85734) UnhandledPromiseRejectionWarning: Error: Provider error: [object Object]
    at /Users/francescoagosti/Projects/0x-api/node_modules/@0x/web3-providers-fork/dist/@0x/web3-providers-fork.cjs.js:332:15
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:85734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:85734) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:85734) UnhandledPromiseRejectionWarning: Error: Failed to establish under-the-hood heartbeat subscription
    at WSClient.<anonymous> (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:489:31)
    at step (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:32:23)
    at Object.throw (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:13:53)
    at rejected (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:5:65)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:85734) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

Along with catching this error immediately after.
```
[1572987407003] ERROR (85734 on 0x): Connection error: Connection is not open on send()
    Error: Connection error: Connection is not open on send()
        at /Users/francescoagosti/Projects/0x-api/node_modules/@0x/web3-providers-fork/dist/@0x/web3-providers-fork.cjs.js:503:27
        at new Promise (<anonymous>)
        at WebsocketProvider.sendPayload (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/web3-providers-fork/dist/@0x/web3-providers-fork.cjs.js:497:14)
        at WebsocketProvider._callee$ (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/web3-providers-fork/dist/@0x/web3-providers-fork.cjs.js:188:29)
        at tryCatch (/Users/francescoagosti/Projects/0x-api/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/francescoagosti/Projects/0x-api/node_modules/regenerator-runtime/runtime.js:271:22)
        at Generator.prototype.(anonymous function) [as next] (/Users/francescoagosti/Projects/0x-api/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/Users/francescoagosti/Projects/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/Users/francescoagosti/Projects/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
        at /Users/francescoagosti/Projects/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
        at new Promise (<anonymous>)
        at WebsocketProvider.<anonymous> (/Users/francescoagosti/Projects/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
        at WebsocketProvider.send (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/web3-providers-fork/dist/@0x/web3-providers-fork.cjs.js:207:22)
        at WSClient.<anonymous> (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:324:63)
        at step (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:32:23)
        at Object.next (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/mesh-rpc-client/lib/src/ws_client.js:13:53)
```

Ideally it would not have the unhandledPromiseRejection error.

**Comment by nabakirov** [comment]
Have the same issue when running mesh on mainnet network. In ropsten testnet works great

**Comment by nabakirov** [comment]
Figured out that mesh version 6.0.0-beta has this issue. Mesh client works with mesh version 5.1.0-beta

**Comment by jgostylo** [comment]
I am having this same issue I believe.  I set up a mesh node in a local docker container forwarding the ports.  I set up a standard node app (node v12.13.1) and install the typescript json-rpc client with the yarn install.  I just grabbed this today so the client version is "^6.1.1-beta".    My code is the following:

```javascript
const meshclient = require('@0x/mesh-rpc-client')

mesh = new meshclient.WSClient("ws://127.0.0.1:60557")
```

and the error I am getting looks like this:

```
(node:9040) UnhandledPromiseRejectionWarning: Error: Failed to establish under-the-hood heartbeat subscription
    at WSClient.<anonymous> (D:\projects\0xmeshclient\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:490:31)
    at step (D:\projects\0xmeshclient\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:32:23)
    at Object.throw (D:\projects\0xmeshclient\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:13:53)
    at rejected (D:\projects\0xmeshclient\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:5:65)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:9040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Please note that the line numbers won't line up because I put in some console.log() for attempted debugging.

**Comment by jgostylo** [comment]
By way of another update I just tried a straight WebSocket connection with port 60557.  This is my error:

```
Connect Error: Error: socket hang up
```

```javascript
const WebSocket = require('websocket').client

const client = new WebSocket()

client.on("connectFailed", function(error){
  console.log('Connect Error: ' + error.toString());
})

client.on("connect", function(connection){
  console.log("We connected to the WS");
  connection.on("error", function(error){
    console.log("Error on established connection: ", error.toString());
  });
  connection.on("close", function(error){
    console.log("Connection closed");
  });
  connection.on("message", (message) => {
    if (message.type === 'utf8') {
      console.log("Received: '" + message.utf8Data + "'");
    }
  });
});


client.connect("ws://127.0.0.1:60557", "mesh-connector");

var repeat = function(){
  console.log("Heartbeat");
}

setInterval(repeat, 4000);
```

I tried wss as well as ws just in case.  Does this mean there is an issue with the node as it is hanging up on my web socket?

**Comment by sunnyRK** [comment]
My docker image is running. I am not able to get stats and I got below error. can anybody help?
```
(async () => {
    try {    
        const c = new WSClient("ws://localhost:60557");
        console.log(c);
        **const stats = await c.getStatsAsync();**
        console.log(JSON.stringify(stats));
        process.exit(0);
    } catch (error) {
        console.log(error);
    }
})()

```
**(node:32432) UnhandledPromiseRejectionWarning: Error: Failed to establish under-the-hood heartbeat subscription**
    at WSClient.<anonymous> (C:\A Computer\Blockchain\0x-Mesh\mesh-workshop-demo\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:349:31)
    at step (C:\A Computer\Blockchain\0x-Mesh\mesh-workshop-demo\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:32:23)
    at Object.throw (C:\A Computer\Blockchain\0x-Mesh\mesh-workshop-demo\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:13:53)
    at rejected (C:\A Computer\Blockchain\0x-Mesh\mesh-workshop-demo\node_modules\@0x\mesh-rpc-client\lib\src\ws_client.js:5:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32432) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32432) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js 
process with a non-zero exit code.

**Comment by TamirTian** [comment]
I have the same problem
```js
const meshclient = require('@0x/mesh-rpc-client')

new meshclient.WSClient('ws://127.0.0.1:60557')
  .getStatsAsync()
  .then(console.log)
  .catch(console.error)
```

**Comment by TamirTian** [comment]
I just run
```bash
docker run \                                                                                                                                                                                                                                          
--restart unless-stopped \
-p 60557:60557 \
-p 60558:60558 \
-p 60559:60559 \
-e ETHEREUM_CHAIN_ID="1" \
-e ETHEREUM_RPC_URL="TODO" \
-e VERBOSITY=5 \
-v $(pwd)/0x_mesh:/usr/mesh/0x_mesh \
0xorg/mesh:latest
```
```js
const meshclient = require('@0x/mesh-rpc-client')

function main () {
  const client = new meshclient.WSClient('ws://127.0.0.1:60557')
  setTimeout(() => {
    client.getStatsAsync()
      .then(console.log)
      .catch(console.error)
  }, 3000)

}
main()
```

**Comment by robert-e-davidson3** [comment]
You might try specifying `-e RPC_ADDR=0.0.0.0:60557`

**Comment by fabioberger** [comment]
Yep, @robert-e-davidson3 suggestion should help together with `new meshclient.WSClient('ws://localhost:60557')`.

If you are on Windows, you might not be able to use `localhost`, but instead must run `docker-machine ip default` and use the returned ip address. More info on this [here](https://www.jhipster.tech/tips/020_tip_using_docker_containers_as_localhost_on_mac_and_windows.html)

**Comment by TamirTian** [comment]
@robert-e-davidson3 
The `Client` and `Server` ran on my MacOS

**Comment by Maskoteer** [comment]
@robert-e-davidson3 thank you very much
it took me long time tryin to find out what the prob is.
