### ISSUE TITLE
Browser example failure

### ISSUE THREAD

**Issue by fabioberger** [0xProject/0x-mesh#677]
# Context

- `release/8.2.0` branch which cherry-picks some commits into `master`
- Running the browser example
- Golang v1.12.15
- I recently upgraded to Mac OSX 10.15.2 (Catalina) and had some issues with Go versions and getting Go programs to compile. Seems fixed by upgrading explictly to Go v1.12.15.

# Expected Behavior

The example works.

# Current Behavior

Browser Mesh crashes.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Checkout `release/8.2.0`
2. `cd browser; yarn; yarn build`
3. Edit the browser example to include calls to `getStatsAsync`, `getOrdersAsync` and `getOrdersForPageAsync`.
4. `cd ../examples/browser; yarn install --force; yarn build; `
5. Open browser to `localhost:8000`

Example edits to example:

```
    const stats = await mesh.getStatsAsync();
    console.log("getStatsAsync result:", stats);

    const orderResults = await mesh.getOrdersAsync(10);
    console.log("getOrdersAsync result:", orderResults);

    const orderResultsTwo = await mesh.getOrdersForPageAsync(0, 10);
    console.log("getOrdersForPageAsync result:", orderResultsTwo);
```

## Failure Logs

Please include any relevant log snippets or files here.

```
panic: ValueOf: invalid value wasm_exec.js:85:25
<empty string> wasm_exec.js:85:25
goroutine 711 [running]: wasm_exec.js:85:25
syscall/js.ValueOf(0x9ab80, 0xc0f61a0, 0x0) wasm_exec.js:85:25
	/usr/local/opt/go/libexec/src/syscall/js/js.go:176 +0x141 wasm_exec.js:85:25
main.(*MeshWrapper).GetStats(0xdb11db0, 0x11c6000c, 0xc11e330, 0xc064f90) wasm_exec.js:85:25
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:235 +0x8 wasm_exec.js:85:25
main.(*MeshWrapper).JSValue.func4.1(0x7ff8000300000010, 0x36d398, 0x7ff8000300000b8e, 0x2c7) wasm_exec.js:85:25
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:275 +0x2 wasm_exec.js:85:25
main.wrapInPromise.func1.1(0xd381600, 0xc1bcf70, 0x7ff8000300000b92, 0x7ff8000300000b91) wasm_exec.js:85:25
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:319 +0x6 wasm_exec.js:85:25
created by main.wrapInPromise.func1 wasm_exec.js:85:25
	/Users/rickmorty/Documents/projects/0x/0x-mesh/browser/go/main.go:317 +0x4
```

**Comment by fabioberger** [comment]
This issue has been fixed by cherry-picking some additional changes from development into my branch.
