### ISSUE TITLE
Installing Mesh RPC 9.0.0

### ISSUE THREAD

**Issue by fragosti** [0xProject/0x-mesh#719]
# Context

I installed `@0x/mesh-rpc-client@^9.0.0`

# Expected Behavior

For my app to run.

# Current Behavior

```
Error: Cannot find module 'ethereumjs-vm/dist/state/promisified'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/francescoagosti/Projects/0x-api/node_modules/@0x/asset-swapper/node_modules/@0x/base-contract/src/index.ts:31:1)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
```

# Failure Information (for bugs)

This is my entire diff
```
diff --git a/docker-compose.yml b/docker-compose.yml
index 52f7081..e25b232 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,7 +17,7 @@ services:
         ports:
             - "5432:5432"
     mesh:
-        image: 0xorg/mesh:8.1.1
+        image: 0xorg/mesh:9.0.0
         depends_on:
             - ganache
         restart: on-failure
diff --git a/package.json b/package.json
index a03fbb4..fa06cbd 100644
--- a/package.json
+++ b/package.json
@@ -55,7 +55,7 @@
         "@0x/contract-addresses": "^4.6.0",
         "@0x/contract-wrappers": "^13.6.0",
         "@0x/json-schemas": "^5.0.4",
-        "@0x/mesh-rpc-client": "^8.1.0",
+        "@0x/mesh-rpc-client": "^9.0.0",
         "@0x/order-utils": "^10.1.1",
         "@0x/subproviders": "^6.0.4",
         "@0x/utils": "^5.2.0",
diff --git a/yarn.lock b/yarn.lock
index 30d099f..a4fc52d 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -443,9 +443,10 @@
     uuid "^3.3.2"
     websocket "^1.0.29"
 
-"@0x/mesh-rpc-client@^8.1.0":
-  version "8.1.0"
-  resolved "https://registry.npmjs.org/@0x/mesh-rpc-client/-/mesh-rpc-client-8.1.0.tgz#fd7f2a55807207b23bafffe46749388a9539f52c"
+"@0x/mesh-rpc-client@^9.0.0":
+  version "9.0.0"
+  resolved "https://registry.npmjs.org/@0x/mesh-rpc-client/-/mesh-rpc-client-9.0.0.tgz#9349e8797cb3f42fe2ce6ebeac83490ff27841ba"
+  integrity sha512-9Zw6u202jamu4ELRn77IeqlYa7HyjWBdJLjMgnaXuu/YECi6PZwv+9a9WuX86f466llfKnUAqRGnqo9BtZF9nA==
   dependencies:
     "@0x/assert" "^3.0.2"
     "@0x/types" "^3.1.1"

```

**Comment by fragosti** [comment]
`rm -rf node_modules && yarn install` worked
