### ISSUE TITLE
Improve error messages in the `@0x/mesh-rpc-client` package

### ISSUE THREAD

**Issue by jalextowle** [0xProject/0x-mesh#798]
## Description
While the `WSClient` provided by the `@0x/mesh-rpc-client` works correctly (at least for all of the scenarios tested in its test suite), it is somewhat prone to abuse. For example, it is not difficult to call `destroy` more than once in a large and complicated package. In this case, an error will be surfaced from `WSClient.destroy` that looks like this:

```
Error: Connection error: Connection is not open on send()
    at /Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:560:27
    at new Promise (<anonymous>)
    at WebsocketProvider.sendPayload (/Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:554:14)
    at WebsocketProvider._callee$ (/Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:188:29)
    at tryCatch (/Users/alextowle/0x-api/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/alextowle/0x-api/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/alextowle/0x-api/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/alextowle/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/alextowle/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /Users/alextowle/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at WebsocketProvider.<anonymous> (/Users/alextowle/0x-api/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at WebsocketProvider.send (/Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:207:22)
    at WebsocketProvider.unsubscribe (/Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:366:21)
    at /Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:388:45
    at Map.forEach (<anonymous>)
    at WebsocketProvider.clearSubscriptions (/Users/alextowle/0x-api/node_modules/web3-providers/dist/web3-providers.cjs.js:384:28)
    at MeshClient.WSClient.destroy (/Users/alextowle/0x-api/node_modules/@0x/mesh-rpc-client/src/ws_client.ts:423:26)
    at Object.<anonymous> (/Users/alextowle/0x-api/src/app.ts:126:33)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/alextowle/0x-api/lib/src/app.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
error Command failed with exit code 1.
```

This error message is fairly unintuitive and is not particularly user friendly.

### Bonus
Better test all of the endpoints provided by `WSClient` to ensure that they will all provide good error messages in the failure cases.

**Comment by albrow** [comment]
Closing this because the JSON-RPC API will be removed in v10.
